import { ISourceInfo, Platforms } from "../models/types"

export const ECommerceInfo: Record<Platforms, ISourceInfo> = {
    [Platforms.Shopee]: {
        key: Platforms.Shopee,
        name: "shopee",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/icon_favicon_1_96.wI1aMs.png",
        logo: "https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/icon_favicon_1_96.wI1aMs.png",
        domain: "shopee.vn",
    },
    [Platforms.Lazada]: {
        key: Platforms.Lazada,
        name: "lazada",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://lzd-img-global.slatic.net/g/tps/tfs/TB1e_.JhHY1gK0jSZTEXXXDQVXa-64-64.png",
        logo: "https://lzd-img-global.slatic.net/g/tps/tfs/TB1e_.JhHY1gK0jSZTEXXXDQVXa-64-64.png",
        domain: "lazada.vn",
    },
    [Platforms.Tiki]: {
        key: Platforms.Tiki,
        name: "tiki",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://salt.tikicdn.com/ts/upload/29/ca/02/e39713d1b90405fd0d39b8fac676bb0d.png",
        logo: "https://salt.tikicdn.com/ts/upload/29/ca/02/e39713d1b90405fd0d39b8fac676bb0d.png",
        domain: "tiki.vn",
    },
    [Platforms.Sendo]: {
        key: Platforms.Sendo,
        name: "sendo",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://media3.scdn.vn/img4/2020/12_17/ESU8qhSA4W2ha9ONanHH.png",
        logo: "https://media3.scdn.vn/img4/2020/12_17/ESU8qhSA4W2ha9ONanHH.png",
        domain: "sendo.vn",
    },
    [Platforms.Fptshop]: {
        key: Platforms.Fptshop,
        name: "fptshop",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://fptshop.com.vn/favicon.ico",
        logo: "https://fptshop.com.vn/favicon.ico",
        domain: "fptshop.com.vn",
    },
    [Platforms.Viettelstore]: {
        key: Platforms.Viettelstore,
        name: "viettelstore",
        language: ["vi"],
        locale: "vi_VN",
        icon: "https://viettelstore.vn/favicon.ico",
        logo: "https://viettelstore.vn/favicon.ico",
        domain: "viettelstore.vn",
    },
    [Platforms.Tokopedia]: {
        key: Platforms.Tokopedia,
        name: "tokopedia",
        language: ["en"],
        locale: "id_ID",
        icon: "https://images.tokopedia.net/assets-tokopedia-lite/prod/icon144.png",
        logo: "https://images.tokopedia.net/assets-tokopedia-lite/prod/icon144.png",
        domain: "tokopedia.com",
    },
    [Platforms.Bukalapak]: {
        key: Platforms.Bukalapak,
        name: "bukalapak",
        language: ["en"],
        locale: "id_ID",
        icon: "https://assets.bukalapak.com/sigil/bukalapak-logo-icon.svg",
        logo: "https://assets.bukalapak.com/sigil/bukalapak-logo-icon.svg",
        domain: "bukalapak.com",
    },
    [Platforms.Coupang]: {
        key: Platforms.Coupang,
        name: "coupang",
        language: ["ko"],
        locale: "ko_KR",
        icon: "https://image9.coupangcdn.com/image/coupang/favicon/v2/favicon.ico",
        logo: "https://image9.coupangcdn.com/image/coupang/favicon/v2/favicon.ico",
        domain: "coupang.com",
    },
    [Platforms.Gmarket]: {
        key: Platforms.Gmarket,
        name: "gmarket",
        language: ["ko"],
        locale: "ko_KR",
        icon: "https://image.gmarket.co.kr/favicon/gmarket.ico",
        logo: "https://image.gmarket.co.kr/favicon/gmarket.ico",
        domain: "gmarket.co.kr",
    },
}

export const DELAY_TYPE_KEY = 100
