import { ISourceInfo, Platforms } from "../models/types";

export const PlatformsInfo: Record<Platforms, ISourceInfo> = {
  [Platforms.Shopee]: {
    key: Platforms.Shopee,
    name: "shopee",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "shopee.vn",
  },
  [Platforms.Lazada]: {
    key: Platforms.Lazada,
    name: "lazada",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "lazada.vn",
  },
  [Platforms.Tiki]: {
    key: Platforms.Tiki,
    name: "tiki",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "tiki.vn",
  },
  [Platforms.Sendo]: {
    key: Platforms.Sendo,
    name: "sendo",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "sendo.vn",
  },
  [Platforms.Fptshop]: {
    key: Platforms.Fptshop,
    name: "fptshop",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "fptshop.com.vn",
  },
  [Platforms.Viettelstore]: {
    key: Platforms.Viettelstore,
    name: "viettelstore",
    language: ["vi"],
    locale: "vi_VN",
    icon: "",
    logo: "",
    domain: "viettelstore.vn",
  },
};
